version: "3"
services:
  db:
    image: hausgold/postgres:9.6
    network_mode: bridge
    ports: 
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      MDNS_HOSTNAME: "${POSTGRES_HOST}"

  jabber:
    image: rroemhild/ejabberd
    network_mode: bridge
    ports: ["4560:4560", "5222:5222", "5269:5269", "5280:5280", "5443:5443"]
    volumes:
      - ./configs/ejabberd.yml:/etc/ejabberd/ejabberd.yml
    links:
      - db
    environment:
      MDNS_HOSTNAME: "${MDNS_HOSTNAME}"
